---
kind: Namespace
apiVersion: v1
metadata:
  name: exo3
  labels:
    name: exo3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flaskapp
  namespace: exo3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      namespace: exo3
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flaskapp
        image: bbonnefoy/exo3flaskapp:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
    
---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  namespace: exo3
  labels:
    app: mariadb
spec:
  containers:
  - name: mariadb
    image: mariadb:10.9
    env:
    - name: MARIADB_ROOT_PASSWORD
      value: "juve"
    - name: MARIADB_USER
      value: "delpiero"
    - name: MARIADB_PASSWORD
      value: "juve"
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 3306
    volumeMounts:
      - mountPath: /var/lib/mysql
        name: db-volume
  volumes:
        - name: db-volume
          persistentVolumeClaim:
            claimName: db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: flaskapp-svc
  namespace: exo3
spec:
  selector:
    app: flaskapp
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  namespace: exo3
spec:
  selector:
    app: mariadb
  type: ClusterIP
  ports:
  - name: sqlport
    port: 3306
    targetPort: 3306
    protocol: TCP

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: exo3
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
  namespace: exo3
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: flaskapp
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70